### ISSUE TITLE
2-way binding

### ISSUE THREAD

**Issue by thirdreplicator** [fynyky/reactor.js#6]
Is there an easy/slick way you could implement 2-way binding between a data model and a DOM element, like the value of an input field?  That would reproduce half of the magic of a lot of these full-stack JS frameworks like Ember and Angular.

**Comment by pwFoo** [comment]
Any plans to add 2-way bindings to reactor.js?

**Comment by fynyky** [comment]
And years later I have something launched with basic 2 way binding!
